import express, { Response } from "express";
import userController from "../controllers/userController";
import authController from "../controllers/authController";
import { UserRequest } from "../backendTypes";

const userRouter = express.Router();

// Route for user login. Confirms credentials, assigns JWT, creates cookie, and returns user_id
userRouter.post(
  "/login",
  userController.verifyUser,
  authController.assignJwt,
  authController.cookieCreator,
  (_req: UserRequest, res: Response) => {
    const returnedId = res.locals.id as number;
    return res.status(200).json({ user_id: returnedId });
  },
);

// Route for user signup, creates user in DB based off of supplied credentials and returns new user_id generated by MongoDB
userRouter.post(
  "/signup",
  userController.createUser,
  (_req: UserRequest, res: Response) => {
    const returnedId = res.locals.id as number;
    return res.status(201).json({ user_id: returnedId });
  },
);

// Route for user logout, clears cookies
userRouter.get(
  "/logout",
  userController.logout,
  (_req: UserRequest, res: Response) => {
    return res.status(202).json("Successful logout");
  },
);

// Route to delete user, currently only being used for test user
userRouter.delete(
  "/remove/:user_id",
  userController.deleteUser,
  (_req: UserRequest, res: Response) => {
    return res.status(202).json(res.locals.deleted);
  },
);

export default userRouter;
